services:
  weather-api:
    build: .
    container_name: weather-api
    restart: always
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
networks:
  default:
    external:
      name: smartapp-network